Data = Fig371_BaselineConvergenceCache();

Fig371_BaselineConvergenceBarFigure( ...
	Data.ConvergenceRateStruct, ...
	Data.CompareGroup, ...
	'Convergence rate', ...
	'中文图Fig371C_BaselineConvergence_Rate.svg', ...
	cellstr(Data.BarLabels));