% Shared model data cache for Chinese Fig382/Fig383 scripts.

cacheName = 'Fig382383_ModelData';
cacheVersion = 1;
seedBase = 38238304;
permutationCount = 10000;
permutationSeed = 1;

useCachedData = false;
if evalin('base', sprintf('exist(''%s'', ''var'')', cacheName)) == 1
	Fig382383Data = evalin('base', cacheName);
	useCachedData = iIsReusableFig382383Data(Fig382383Data, cacheVersion, seedBase, permutationCount, permutationSeed);
end

if ~useCachedData
	Fig382383Data = TransferLearning.THModel.BuildFig382383SharedModelData( ...
		SeedBase=seedBase, ...
		NPermutation=permutationCount, ...
		PermutationSeed=permutationSeed);
	assignin('base', cacheName, Fig382383Data);
end

function tf = iIsReusableFig382383Data(data, cacheVersion, seedBase, permutationCount, permutationSeed)
tf = isstruct(data) ...
	&& isfield(data, 'CacheVersion') && isequal(data.CacheVersion, cacheVersion) ...
	&& isfield(data, 'SeedBase') && isequal(data.SeedBase, seedBase) ...
	&& isfield(data, 'NPermutation') && isequal(data.NPermutation, permutationCount) ...
	&& isfield(data, 'PermutationSeed') && isequal(data.PermutationSeed, permutationSeed) ...
	&& isfield(data, 'Acceptance') && isfield(data.Acceptance, 'Passed') && isequal(data.Acceptance.Passed, true) ...
	&& isfield(data, 'Performance') && isfield(data.Performance, 'Naive') && isfield(data.Performance, 'Transfer') && isfield(data.Performance, 'THOff') ...
	&& isfield(data, 'PreFormalWeightValues') ...
	&& isfield(data, 'Heterogeneity') ...
	&& isfield(data, 'Sigmoid') && isfield(data.Sigmoid, 'Fig382C') && isfield(data.Sigmoid, 'Fig383B') ...
	&& isfield(data, 'HeatmapData');
end