Data = Fig371_BaselineConvergenceCache();

Fig371_BaselineConvergenceBarFigure( ...
	Data.FluorescenceDeltaStruct, ...
	Data.CompareGroup, ...
	'(F_{-0.3}/F_{-3})-1', ...
	'中文图Fig371D_BaselineConvergence_FluorescenceDelta.svg', ...
	cellstr(Data.BarLabels));