Data = Fig71_BaselineConvergenceCache();

Fig71_BaselineConvergenceBarFigure( ...
	Data.ConvergenceRateStruct, ...
	Data.CompareGroup, ...
	'Convergence rate', ...
	'中文图Fig71C_BaselineConvergence_Rate.svg', ...
	cellstr(Data.BarLabels));