Data = Fig71_BaselineConvergenceCache();

Fig71_BaselineConvergenceBarFigure( ...
	Data.FluorescenceDeltaStruct, ...
	Data.CompareGroup, ...
	'(F_{-0.3}/F_{-3})-1', ...
	'中文图Fig71D_BaselineConvergence_FluorescenceDelta.svg', ...
	cellstr(Data.BarLabels));