function [Approved, Comment] = FilterEvaluate(Request)
% FilterEvaluate - 审查 Agent 发来的 MATLAB 代码请求
%   包含危险关键词的命令将被拒绝，并返回拒绝理由。
%
%   Input:
%       Request - 字符串，Agent 提交的 MATLAB 代码
%   Output:
%       Approved - logical，true 表示批准执行
%       Comment  - 字符串，拒绝时提供理由，批准时为空字符串

    % 默认批准
    Approved = true;
    Comment = '';

    % 转为小写便于关键词匹配
    requestLower = lower(Request);

    % 定义禁止的关键词及其拒绝理由
    % 格式: {keyword, reason} 对，逐一检查
    forbiddenKeywords = { ...
        'clear',       '`clear` may clear workspace variables that other MCP tools depend on'; ...
        'clearvars',   '`clearvars` may clear workspace variables'; ...
        'eval',        '`eval` is unsafe and can execute arbitrary code'; ...
        'evalc',       '`evalc` is unsafe and can execute arbitrary code'; ...
        'evalin',      '`evalin` is unsafe and can execute arbitrary code'; ...
        'assignin',    '`assignin` bypasses normal variable scoping rules'; ...
        'system',      '`system`/`dos`/`unix` can execute arbitrary OS commands'; ...
        'dos',         '`dos` can execute arbitrary OS commands'; ...
        'unix',        '`unix` can execute arbitrary OS commands'; ...
        'delete',      '`delete` can remove files from the filesystem'; ...
        'rmdir',       '`rmdir` can remove directories from the filesystem'; ...
        'fclose all',  '`fclose(''all'')` can disrupt MCP server file handles'; ...
        'fclose',      '`fclose` can close file handles used by the MCP server'; ...
        'quit',        '`quit`/`exit` will terminate the MATLAB session'; ...
        'exit',        '`exit` will terminate the MATLAB session'; ...
        'bdclose',     '`bdclose` can close Simulink models'; ...
        '!',           '`!` can execute arbitrary OS commands' ...
    };

    % 逐项检查
    for i = 1:size(forbiddenKeywords, 1)
        keyword = forbiddenKeywords{i, 1};
        reason  = forbiddenKeywords{i, 2};
        if contains(requestLower, keyword)
            Approved = false;
            Comment = ['Request rejected: ' reason];
            return;
        end
    end
end
