#pragma once
#include <stdint.h>
/* 本文件定义了所有的UID枚举值，作为模块、异常、信息字段等的唯一标识符，在Arduino端和PC端之间传递信息时使用，且必须保持一致。
用户可以在此文件中添加自定义的UID枚举值，但请勿修改已有的枚举值，否则可能导致Arduino端和PC端之间无法正确通信。
*/
enum class UID : uint8_t {
	// Arduino提供的服务端口

	PortA_PointerSize,
	PortA_CreateProcess,
	PortA_StartModule,
	PortA_RestoreModule,
	PortA_PauseProcess,
	PortA_ContinueProcess,
	PortA_AbortProcess,
	PortA_GetInformation,
	PortA_DeleteProcess,
	PortA_AllProcesses,
	PortA_RandomSeed,
	PortA_IsReady,
	PortA_ProcessValid,

	// Computer提供的服务端口

	PortC_ProcessFinished,
	PortC_Signal,
	PortC_TrialStart,
	PortC_Exception,
	PortC_ImReady,
	PortC_Debug,

	// 运行时异常

	Exception_Success,
	Exception_InvalidProcess,
	Exception_MethodNotSupported,
	Exception_StillRunning,
	Exception_ProcessNotRunning,
	Exception_ProcessNotPaused,
	Exception_ProcessNotIdle,
	Exception_ProcessFinished,
	Exception_BrokenStartArguments,
	Exception_BrokenRestoreArguments,
	Exception_MethodNotImplemented,
	Exception_InvalidModule,

	// 信息字段

	Field_After,
	Field_Do,
	Field_ID,
	Field_RandomDuration,
	Field_Duration,
	Field_AbortStep,
	Field_StartModule,
	Field_Modules,
	Field_Range,
	Field_Target,
	Field_Pin,
	Field_Monitor,
	Field_Content,
	Field_Message,
	Field_HighOrLow,
	Field_Cleaner,
	Field_Period,
	Field_Times,
	Field_PeriodA,
	Field_PeriodB,
	Field_ContentA,
	Field_ContentB,
	Field_TargetID,
	Field_Slot,
	Field_Value,
	Field_Unit,

	// 表列

	Column_SubSteps,
	Column_Repeats,
	Column_Module,

	// 信息字段数据类型

	Type_Bool,
	Type_UInt8,
	Type_UInt16,
	Type_UInt32,
	Type_UID,
	Type_Array,
	Type_Struct,
	Type_Seconds,
	Type_Milliseconds,
	Type_Microseconds,
	Type_Infinite,
	Type_Table,
	Type_Pointer,
	Type_Map,

	// 进程状态

	State_Ready,
	State_Running,
	State_Paused,
	State_Aborted,
	State_Finished,
	State_Normal,
	State_Repeat,
	State_Restore,
	State_Idle,

	// 信号事件

	Event_TrialStart,
	Event_ConnectionReset,
	Event_MonitorHit,
	Event_MonitorMiss,
	Event_ProcessPaused,
	Event_ProcessContinue,
	Event_ProcessAborted,
	Event_AudioUp,
	Event_AudioDown,
	Event_LightUp,
	Event_LightDown,
	Event_Water,
	Event_AirPuff,
	Event_HitCount,
	Event_HFImage,
	Event_LFImage,
	Event_Optogenetic,
	Event_Image,
	Event_LowUp,
	Event_LowDown,
	Event_HighUp,
	Event_HighDown,
	Event_Debug,
	Event_LaserUp,
	Event_LaserDown,
	Event_CorrectReject,
	Event_FalseChoice,
	Event_Pulse2,
	Event_Pulse3,
	Event_Pulse4,
	Event_Pulse5,
	Event_AreaIn,
	Event_LickBegin,



	// 测试

	Test_BlueLed,
	Test_WaterPump,
	Test_CapacitorReset,
	Test_CapacitorMonitor,
	Test_CD1,
	Test_ActiveBuzzer,
	Test_AirPump,
	Test_HostAction,
	Test_SquareWave,
	Test_RandomFlash,
	Test_LowTone,
	Test_HighTone,
	Test_Optogenetic,
	Test_MultiOptoDoubleAudioTask2,

	// 回合

	Trial_Invalid,
	Trial_AudioWater,
	Trial_LightWater,
	Trial_AudioOnly,
	Trial_LightOnly,
	Trial_WaterOnly,
	Trial_HighWater,
	Trial_HighWaterAlways,
	Trial_LowAir,
	Trial_OptoHighWater,
	Trial_OptoLowAir,
	Trial_MultiOptoHighWater,
	Trial_MultiOptoLowAir,
	Trial_HLWater,
	Trial_HLWaterAlways,
	Trial_OptoHLWaterAlways,
	Trial_OptoHLWater,
	Trial_OptoHHAir,
	Trial_OptoLHAir,
	Trial_OptoLLAir,
	Trial_MultiOptoHLWaterAlways,
	Trial_MultiOptoHLWater,
	Trial_MultiOptoHHAir,
	Trial_MultiOptoLHAir,
	Trial_MultiOptoLLAir,
	Trial_MultiOptoLaserOnly,
	Trial_HHAir,
	Trial_LHAir,
	Trial_LLAir,
	Trial_RandomMultiOptoHLWater,
	Trial_RandomMultiOptoHHAir,
	Trial_RandomMultiOptoLHAir,
	Trial_RandomMultiOptoLLAir,
	Trial_MultiOptoHLHWater,
	Trial_MultiOptoHHHAir,
	Trial_MultiOptoLHHAir,
	Trial_MultiOptoLLHAir,
	Trial_MultiOptoHLLAir,
	Trial_MultiOptoHHLAir,
	Trial_MultiOptoLHLAir,
	Trial_MultiOptoLLLAir,
	Trial_HLHWater,
	Trial_HLHLWater,
	Trial_MultiOptoHLHLWater,
	Trial_MultiOptoHHLLAir,
	Trial_MultiOptoLHLLAir,
	Trial_MultiOptoLLLLAir,
	Trial_MultiOptoHLHHAir,
	Trial_MultiOptoHHHHAir,
	Trial_MultiOptoLLHLAir,
	Trial_MultiOptoHLLLAir,
	Trial_MultiOptoLHHHAir,
	Trial_MultiOptoLLHHAir,
	Trial_MultiOptoHLLHAir,
	Trial_MultiOptoHHHLAir,
	Trial_MultiOptoLHHLAir,
	Trial_MultiOptoHHLHAir,
	Trial_MultiOptoLHLHAir,
	Trial_MultiOptoLLLHAir,
	Trial_Shaping,
	Trial_MultiOptoLHLWater,
	Trial_MultiOptoHLHAir,
	Trial_MultiOptoHLHLWaterAlways,
	Trial_MultiOptoHLWater2,

	
	// 持续时间类型

	Integer_Random,
	Duration_Infinite,

	// 基础模块

	Module_Sequential,
	Module_RandomSequential,
	Module_Delay,
	Module_Abort,
	Module_Restart,
	Module_Randomize,
	Module_MonitorPin,
	Module_SerialMessage,
	Module_DigitalWrite,
	Module_CleanWhenAbort,
	Module_Async,
	Module_RepeatEvery,
	Module_DoubleRepeat,
	Module_Repeat,
	Module_DigitalToggle,
	Module_AssignModuleID,
	Module_ReferModuleID,
	Module_DynamicSlot,
	Module_LoadSlot,
	Module_ClearSlot,
	Module_ResponseWindow,
	Module_RandomInteger,
	Module_ConstantInteger,
	Module_LickDetector,
	Module_Water,
	Module_RightDetector,
	Module_FalseDetector,
	Module_WaterAlwaysDetector,
	Module_ResponseWindow0,
	Module_ResponseWindow2,
	Module_Laser,
	Module_MonitorRestartRight,
	Module_MonitorRestartFalse,
	Module_WaitingTime2,
	Module_Skip,

	// 主机动作

	Host_GratingImage,
	Host_StartRecord,

	// 会话

	Session_AudioWater,
	Session_LightWater,
	Session_LAuW,
	Session_SingleAudioShaping,
	Session_OptoSingleAudioTask,
	Session_OptoDoubleAudioTask,
	Session_MultiOptoSingleAudioTask,
	Session_DoubleAudioShaping,
	Session_MultiOptoDoubleAudioTask,
	Session_LaserOnly,
	Session_RandomMultiOptoDoubleAudioTask,
	Session_DoubleAudioTask,
	Session_MultiOptoTripeAudioTask,
	Session_MultiOptoTripeAudioTask2,
	Session_QuadrupleAudioShaping,
	Session_MultiOptoQuadrupleAudioTask,
	Session_MultiOptoDoubleAudioTask2,
	Session_Shaping,
	Session_MultiOptoTripeAudioTask3,
	Session_MultiOptoDoubleAudioTask3,
	Session_MultiOptoQuadrupleAudioTask2,
	Session_DoubleAudioRecon

};