function weights = AllConnectionWeights(Mouse)
weights = [ ...
	TransferLearning.THModel.NonSelfInternalWeights(Mouse.W_L23L5ToL23L5); ...
	Mouse.WEI_L23(:); ...
	Mouse.WIE_L23(:); ...
	TransferLearning.THModel.NonSelfInternalWeights(Mouse.WII_L23); ...
	Mouse.WEI_L5RewardRecv(:); ...
	Mouse.WIE_L5RewardRecv(:); ...
	TransferLearning.THModel.NonSelfInternalWeights(Mouse.WII_L5RewardRecv); ...
	Mouse.WEI_L5Read(:); ...
	Mouse.WIE_L5Read(:); ...
	TransferLearning.THModel.NonSelfInternalWeights(Mouse.WII_L5Read); ...
	Mouse.WI23ToL5RewardRecv(:); ...
	Mouse.WI23ToL5Read(:) ...
];
weights = TransferLearning.THModel.GatherValue(weights(:));
weights = weights(isfinite(weights));
end
