function fieldNames = LockedParameterNames()
fieldNames = [ ...
	"NumMice"; ...
	"NumSessions"; ...
	"NumTrials"; ...
	"NCueInput"; ...
	"NL5"; ...
	"NL23L5"; ...
	"Ceiling"; ...
	"TransferHighestAlpha"; ...
	"TransferTHOffFirstSessionHitMax"; ...
	"ClampNegativeActivity"; ...
	"ClampNegativePatterns"; ...
	"NoiseFirstStateCarryover"; ...
	"MaxPretrainSessions"; ...
	"NoiseCueBacktrainMaxAttempts"];
end
