function fieldNames = TunableParameterNames()
fieldNames = [ ...
	"NL23"; ...
	"NL5Read"; ...
	"NL5RewardRecv"; ...
	"NIL23"; ...
	"NIL5RewardRecv"; ...
	"NIL5Read"; ...
	"HitThreshold"; ...
	"RecurrentPasses"; ...
	"DecisionIterationEarlyWeightDecay"; ...
	"NoiseCueBacktrainRecurrentPasses"; ...
	"THOffTeachingSignalScale"; ...
	"ResponseScale"; ...
	"NoiseScale"; ...
	"InhibitorySuppressionGain"; ...
	"CueInputGain"; ...
	"CueInputGainPretrain"; ...
	"InitWeightMin"; ...
	"WeightMax"; ...
	"ExcitatoryPostActivityThreshold"; ...
	"HebbRate"; ...
	"CueModalityCorr"];
end
