function fieldNames = TunableParameterNames()
fieldNames = [ ...
	"NL23"; ...
	"NReward"; ...
	"NL5Read"; ...
	"NL5RewardRecv"; ...
	"NIL23"; ...
	"NIL5RewardRecv"; ...
	"NIL5Read"; ...
	"HitThreshold"; ...
	"RecurrentPasses"; ...
	"ResponseScale"; ...
	"NoiseCue"; ...
	"NoiseRew"; ...
	"NoiseRead"; ...
	"Comp_Cue"; ...
	"Comp_Rew"; ...
	"Comp_Read"; ...
	"CueInputGain"; ...
	"NoiseCueBacktrainInputGain"; ...
	"CueInputGainPretrain"; ...
	"RewInputGain"; ...
	"THRewardRecvInputGain"; ...
	"ReadInputGain"; ...
	"THReadInputGain"; ...
	"THReadHeterogeneityGain"; ...
	"InitWeightDistributionMode"; ...
	"InitWeightChiSquareDof"; ...
	"InitExcWeightMean"; ...
	"InitExcWeightStd"; ...
	"WCap"; ...
	"AfferentWCap"; ...
	"RewardAfferentNorm"; ...
	"HebbRate"; ...
	"FormalHebbGainStd"; ...
	"FormalHebbGainMin"; ...
	"FormalHebbGainMax"; ...
	"FormalHitTeachingScale"; ...
	"InhPlasticityRate"; ...
	"InhTargetAct"; ...
	"InhWeightMax"; ...
	"InitInhWeightMean"; ...
	"InitInhWeightStd"; ...
	"IToIGain"; ...
	"CueModalityCorr"; ...
	"OvernightRetention"; ...
	"OvernightNoise"];
end
