%[text] 本函数负责将英文的原始信号UID翻译为中文输出到命令行窗口。
function LogString = LogTranslate(Log)
import Gbec.UID
persistent Dict
if isempty(Dict)
	Dict=dictionary(...
		UID.Host_StartRecord,		"开始拍摄",...
		UID.Event_LightUp,			"灯光亮",...
		UID.Event_LightDown,		"灯光灭",...
		UID.Event_AudioUp,			"声音响",...
		UID.Event_AudioDown,		"声音停",...
		UID.Event_MonitorHit,		"命中",...
		UID.Event_MonitorMiss,		"错失",...
		UID.Event_Water,			"给水",...
		UID.Event_AirPuff,			"喷气",...
		UID.Event_HitCount,			"舔",...
		UID.Event_HFImage,			"高频图",...
		UID.Event_LFImage,			"低频图",...
		UID.Event_TrialStart,		"回合开始",...
		UID.Event_ProcessAborted,	"会话已放弃",...
		UID.Event_Image,			"图像",...
		UID.Event_LowUp,			"低音响",...
		UID.Event_LowDown,			"低音停",...
		UID.Event_HighUp,			"高音响",...
		UID.Event_HighDown,			"高音停",...
		UID.Event_ProcessPaused,	"会话暂停",...
		UID.Event_Optogenetic,		"光遗传",...
		UID.Event_ProcessContinue,	"会话继续",...
        UID.Event_CorrectReject,    "正确",...
	    UID.Event_FalseChoice,      "错误",...
        UID.Event_LaserUp,          "激光亮",...
	    UID.Event_LaserDown,        "激光灭"...
		);
end
%必须考虑有些键有匹配有些键无匹配的情况，不能简单try-catch
KeyLogical=Dict.isKey(Log);
LogString=strings(size(Log));
LogString(KeyLogical)=Dict(Log(KeyLogical));
KeyLogical=~KeyLogical;
LogString(KeyLogical)=string(UID(Log(KeyLogical)));

%[appendix]{"version":"1.0"}
%---
